#!/bin/bash

OP="randread"
#DEVICE="/dev/ram0"
#DEVICE="/dev/nullb0"
DEVICE="/dev/sdc" #Samsung SSD 860 SATA
#DEVICE="/dev/sdb"
#DEVICE="/dev/nvme0n1" #Samsung SSD 970 m.2
#DEVICE="/dev/ramdisk_mq"
#DEVICE="/mnt/ramdisk_mq/aaa"
#DEVICE="/home/kesl/ramdisk_mq/aaa"
#DEVICE="/dev/shm"
#DEVICE="/dev/nvme1n1"
#DEVICE="/home/kesl/re_test_20181206/bio/ramdisk/test"
BSSIZE="4k"

# taskset
#for y in 5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95 100 105 110 115 120
#for y in 120
#do
#    JOB=$y
#    DEPTH="128"
#    NUM=`expr $y - 1`
#    sync;echo 3 > /proc/sys/vm/drop_caches
#    sleep 5
#    echo fio --output=./optane/\_$JOB\_dp:\_$DEPTH.txt --filename=$DEVICE --rw=$OP --iodepth=$DEPTH --numjobs=$JOB
#    sudo taskset -c 0-$NUM fio --output=./numad/job:\_$JOB\_dp:\_$DEPTH.txt --name=myjob --filename=$DEVICE --ioengine=libaio --direct=1 --norandommap --randrepeat=0 --runtime=10 --time_based --blocksize=$BSSIZE --rw=$OP --iodepth=$DEPTH --numjobs=$JOB --group_reporting=1 --gtod_reduce=1 # --numa_cpu_nodes=all --numa_mem_policy=bind:all --fadvise_hint=0

#done


# no taskset 
#for y in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20
#for y in 2 4 6 8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50
#for y in 45 50 55 60 65 70 75 80 85 90 95 100 105 110 115 120
#for y in 10 15 20 25 30 35 40 45 50 55 
#for y in 5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95 100 105 110 115 120
for y in 5 10 15 20 25 30 35 40
#for y in 65 70 75 80 85 90 95 100 105 110 115 120
#for y in 115 120 
do
    JOB=$y
    DEPTH="128"
    NUM=`expr $y - 1`
    TIME=6
    sync;echo 3 > /proc/sys/vm/drop_caches
    sleep 2
    echo fio --output=/home/kesl/fio_macro/data/job:\_$JOB\_dp:\_$DEPTH.txt --filename=$DEVICE --rw=$OP --iodepth=$DEPTH --numjobs=$JOB #--thread
    #sudo fio --output=/home/kesl/re_test_20181206/bio/numad/job:\_$JOB\_dp:\_$DEPTH.txt --name=myjob --filename=$DEVICE --ioengine=libaio --direct=1 --norandommap --randrepeat=0 --size=3G --randseed=25 --blocksize=$BSSIZE --rw=$OP --iodepth=$DEPTH --numjobs=$JOB --group_reporting=1 --gtod_reduce=1 --thread # --numa_cpu_nodes=all --numa_mem_policy=bind:all --fadvise_hint=0
    sudo fio --output=/home/kesl/fio_macro/data/job:\_$JOB\_dp:\_$DEPTH.txt --name=myjob --filename=$DEVICE --ioengine=libaio --direct=1 --norandommap --randrepeat=0 --runtime=$TIME --time_based --blocksize=$BSSIZE --rw=$OP --iodepth=$DEPTH --numjobs=$JOB --gtod_reduce=1 --thread --group_reporting=1 # --numa_cpu_nodes=all --numa_mem_policy=bind:all --fadvise_hint=0

done

